# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_activity_summary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='summary_image',
            field=models.ImageField(null=True, upload_to='summary_images'),
        ),
    ]
