# Generated by Django 2.0.1 on 2018-02-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_boat'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity', to='api.Boat'),
        ),
    ]
